### ISSUE TITLE
Cannot extract the 'train' and 'validation' zip files on colab.

### ISSUE THREAD

**Issue by VirajBagal** [abachaa/VQA-Med-2019#1]
I currently want to train a model on vqa-med 2018 data. I cloned the repo in colab and try to unzip the train and validation zip files. But zipfile.ZipFile(path_to_zip_file) gives the error: **BadZipFile: File is not a zip file**.  It works fine for the test zip file. How do I extract the train and validation zip files?

**Comment by LuisFros** [comment]
I have the same issue. Zips are not working

**Comment by abachaa** [comment]
I copied all the data files here https://zenodo.org/records/10499039

**Comment by abachaa** [comment]
I copied all the data files here: https://zenodo.org/records/10499039
