### ISSUE TITLE
I can't download the dataset

### ISSUE THREAD

**Issue by ghost** [abachaa/VQA-Med-2019#2]
Hello,
It seems that the zip files are corrupted and no one was able to download the dataset, could you please solve this issue because i need the dataset urgently.
Best regards.

**Comment by GanjinZero** [comment]
same issue

**Comment by whtitefall** [comment]
did you resolve this issue? I'm curious what are other sources for this dataset

**Comment by whtitefall** [comment]
> did you resolve this issue? I'm curious what are other sources for this dataset

ok, I figure it out. you need to click on that zip link to download, instead of downloading the whole repo

**Comment by abachaa** [comment]
I copied all the data files here: https://zenodo.org/records/10499039

**Comment by abachaa** [comment]
I copied all the data files here: https://zenodo.org/records/10499039
